In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np
import pandas as pd


In [ ]:
mobile_data=pd.read_csv(r'/content/sample_data/mobile_price.csv')
mobile_data.head(20)

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0    1           1043     1          1.8         1  14       0           5   
1    2            841     1          0.5         1   4       1          61   
2    3           1807     1          2.8         0   1       0          27   
3    4           1546     0          0.5         1  18       1          25   
4    5           1434     0          1.4         0  11       1          49   
5    6           1464     1          2.9         1   5       1          50   
6    7           1718     0          2.4         0   1       0          47   
7    8            833     0          2.4         1   0       0          62   
8    9           1111     1          2.9         1   9       1          25   
9   10           1520     0          0.5         0   1       0          25   
10  11           1500     0          2.2         0   2       0          55   
11  12           1343     0          2.9         0   2       1          34   
12  13            900     1          1.4         1   0       0          30   
13  14           1190     1          2.2         1   5       0          19   
14  15            630     0          1.8         0   8       1          51   
15  16           1846     1          1.0         0   5       1          53   
16  17           1985     0          0.5         1  14       1          26   
17  18           1042     0          2.9         0   5       1          48   
18  19           1231     1          1.7         1   2       1          37   
19  20           1488     0          2.6         0   9       0          37   

    m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0     0.1        193  ...  16        226      1412  3476    12     7   
1     0.8        191  ...  12        746       857  3895     6     0   
2     0.9        186  ...   4       1270      1366  2396    17    10   
3     0.5         96  ...  20        295      1752  3893    10     0   
4     0.5        108  ...  18        749       810  1773    15     8   
5     0.8        198  ...   9        569       939  3506    10     7   
6     1.0        156  ...   3       1283      1374  3873    14     2   
7     0.8        111  ...   2       1312      1880  1495     7     2   
8     0.6        101  ...  19        556       876  3485    11     9   
9     0.5        171  ...  20         52      1009   651     6     0   
10    0.6         80  ...   6        503      1336  3866    13     7   
11    0.8        171  ...   6        235      1671  3911    15     8   
12    1.0         87  ...   3        829      1893   439     6     2   
13    0.9        158  ...  15        227      1856   992    13     0   
14    0.9        193  ...   9       1315      1323  2751    17     6   
15    0.7        106  ...   7        185      1832   563     9     5   
16    1.0        163  ...  17        613      1511  2083    13     3   
17    0.2        186  ...  15        335       532  2187     9     2   
18    0.2        194  ...   3         82      1771  3902    19    12   
19    0.7        189  ...  20         47       559  2524     5     0   

    talk_time  three_g  touch_screen  wifi  
0           2        0             1     0  
1           7        1             0     0  
2          10        0             1     1  
3           7        1             1     0  
4           7        1             0     1  
5           3        1             1     1  
6          10        0             0     0  
7          18        0             1     1  
8          10        1             1     0  
9           5        1             0     1  
10         20        0             1     0  
11          8        1             1     1  
12         20        1             0     0  
13         16        1             1     0  
14          3        1             1     0  
15         10        1             0     1  
16         14        1             1     0  
17          5        1             0     0

In [ ]:
mobile_data.columns

Index(['id', 'battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc',
       'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc',
       'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x=scaler.fit_transform(mobile_data)
x

array([[-1.73031962, -0.47545131,  0.968496  , ..., -1.76021608,
         1.        , -1.01409939],
       [-1.72685552, -0.94278218,  0.968496  , ...,  0.56811207,
        -1.        , -1.01409939],
       [-1.72339142,  1.29207729,  0.968496  , ..., -1.76021608,
         1.        ,  0.98609664],
       ...,
       [ 1.72339142, -0.1469316 , -1.03252879, ...,  0.56811207,
        -1.        , -1.01409939],
       [ 1.72685552,  0.65817305,  0.968496  , ..., -1.76021608,
         1.        , -1.01409939],
       [ 1.73031962,  0.04971753,  0.968496  , ...,  0.56811207,
        -1.        ,  0.98609664]])

In [ ]:
from pandas.core.common import random_state
from sklearn.model_selection import train_test_split
train, test = train_test_split(x, train_size=0.7, random_state=10)
train

array([[ 0.84004506,  0.67436769, -1.03252879, ...,  0.56811207,
        -1.        , -1.01409939],
       [ 0.61141424, -1.46101046, -1.03252879, ..., -1.76021608,
        -1.        , -1.01409939],
       [ 0.24768339, -1.20652335,  0.968496  , ...,  0.56811207,
         1.        ,  0.98609664],
       ...,
       [ 1.71992731, -1.47951861, -1.03252879, ..., -1.76021608,
         1.        ,  0.98609664],
       [-1.2973067 ,  0.47771856, -1.03252879, ..., -1.76021608,
         1.        , -1.01409939],
       [-0.81233223, -0.135364  ,  0.968496  , ...,  0.56811207,
        -1.        , -1.01409939]])

In [ ]:
from sklearn.mixture import GaussianMixture
gm=GaussianMixture(n_components=2, random_state=0).fit(train)
GG=gm.predict(train)
GG


array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,

In [ ]:
from sklearn.metrics import silhouette_score
accuracy=silhouette_score(train, GG)
accuracy

0.06316609157783994

**GAUSSIAN MIXTURE MODEL CLUSTERING ATTEMPT**

In [ ]:
from sklearn.mixture import GaussianMixture
gm=GaussianMixture(n_components=10, random_state=0).fit(train)
GG=gm.predict(train)
GG

array([3, 5, 6, 5, 6, 9, 9, 6, 0, 5, 8, 5, 9, 8, 1, 1, 3, 2, 0, 7, 5, 5,
       4, 5, 2, 9, 3, 5, 5, 8, 1, 5, 6, 9, 5, 2, 2, 8, 4, 2, 3, 3, 0, 9,
       9, 2, 6, 9, 3, 1, 4, 6, 7, 3, 4, 5, 1, 6, 3, 3, 1, 0, 3, 4, 1, 8,
       8, 5, 0, 1, 6, 7, 6, 2, 6, 7, 1, 7, 6, 2, 1, 7, 0, 9, 8, 1, 9, 2,
       9, 0, 4, 9, 8, 1, 7, 7, 2, 6, 9, 1, 5, 3, 1, 7, 6, 5, 2, 8, 5, 3,
       8, 5, 5, 4, 1, 5, 9, 1, 8, 6, 0, 7, 2, 5, 1, 7, 0, 2, 7, 4, 0, 1,
       4, 1, 4, 7, 5, 4, 9, 0, 7, 7, 3, 1, 3, 0, 0, 4, 9, 4, 9, 8, 4, 8,
       1, 6, 4, 9, 8, 9, 5, 5, 6, 9, 9, 8, 5, 0, 6, 1, 4, 9, 9, 9, 5, 1,
       6, 0, 7, 7, 9, 6, 8, 4, 7, 1, 3, 7, 9, 9, 8, 7, 3, 8, 3, 4, 4, 5,
       2, 9, 8, 5, 8, 6, 5, 8, 7, 9, 8, 5, 8, 1, 3, 5, 4, 5, 5, 4, 1, 5,
       2, 5, 9, 4, 4, 7, 6, 9, 5, 7, 9, 3, 3, 8, 6, 5, 4, 1, 9, 5, 2, 6,
       1, 2, 9, 4, 5, 5, 8, 2, 1, 9, 2, 5, 0, 8, 7, 1, 0, 5, 5, 4, 8, 1,
       8, 2, 0, 7, 4, 2, 4, 6, 0, 6, 4, 1, 5, 0, 1, 1, 0, 5, 0, 0, 8, 0,
       0, 8, 6, 7, 9, 8, 0, 3, 3, 0, 7, 0, 1, 8, 2,

In [ ]:
from sklearn.metrics import silhouette_score
accuracy=silhouette_score(train, GG)
accuracy

0.03217155137430124