In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# Importing & Reading the dataset
data = pd.read_csv(r'/content/sample_data/sonar_data.csv')
print("Dataset Shape:",data.shape)
print(data.info())

Dataset Shape: (208, 61)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Freq_1   208 non-null    float64
 1   Freq_2   208 non-null    float64
 2   Freq_3   208 non-null    float64
 3   Freq_4   208 non-null    float64
 4   Freq_5   208 non-null    float64
 5   Freq_6   208 non-null    float64
 6   Freq_7   208 non-null    float64
 7   Freq_8   208 non-null    float64
 8   Freq_9   208 non-null    float64
 9   Freq_10  208 non-null    float64
 10  Freq_11  208 non-null    float64
 11  Freq_12  208 non-null    float64
 12  Freq_13  208 non-null    float64
 13  Freq_14  208 non-null    float64
 14  Freq_15  208 non-null    float64
 15  Freq_16  208 non-null    float64
 16  Freq_17  208 non-null    float64
 17  Freq_18  208 non-null    float64
 18  Freq_19  208 non-null    float64
 19  Freq_20  208 non-null    float64
 20  Freq_21  208 non-null    floa

In [ ]:
#Displaying the data 
data.head(10)

Freq_1  Freq_2  Freq_3  Freq_4  ...  Freq_58  Freq_59  Freq_60  Label
0  0.0200  0.0371  0.0428  0.0207  ...   0.0084   0.0090   0.0032      R
1  0.0453  0.0523  0.0843  0.0689  ...   0.0049   0.0052   0.0044      R
2  0.0262  0.0582  0.1099  0.1083  ...   0.0164   0.0095   0.0078      R
3  0.0100  0.0171  0.0623  0.0205  ...   0.0044   0.0040   0.0117      R
4  0.0762  0.0666  0.0481  0.0394  ...   0.0048   0.0107   0.0094      R
5  0.0286  0.0453  0.0277  0.0174  ...   0.0027   0.0051   0.0062      R
6  0.0317  0.0956  0.1321  0.1408  ...   0.0143   0.0036   0.0103      R
7  0.0519  0.0548  0.0842  0.0319  ...   0.0047   0.0048   0.0053      R
8  0.0223  0.0375  0.0484  0.0475  ...   0.0093   0.0059   0.0022      R
9  0.0164  0.0173  0.0347  0.0070  ...   0.0035   0.0056   0.0040      R

[10 rows x 61 columns]

In [ ]:
print(data.isnull().sum())

Freq_1     0
Freq_2     0
Freq_3     0
Freq_4     0
Freq_5     0
          ..
Freq_57    0
Freq_58    0
Freq_59    0
Freq_60    0
Label      0
Length: 61, dtype: int64


In [ ]:
X = data.iloc[:, 0:59].values
X=X
print(X)

[[0.02   0.0371 0.0428 ... 0.018  0.0084 0.009 ]
 [0.0453 0.0523 0.0843 ... 0.014  0.0049 0.0052]
 [0.0262 0.0582 0.1099 ... 0.0316 0.0164 0.0095]
 ...
 [0.0522 0.0437 0.018  ... 0.014  0.0138 0.0077]
 [0.0303 0.0353 0.049  ... 0.0034 0.0079 0.0036]
 [0.026  0.0363 0.0136 ... 0.004  0.0036 0.0061]]


In [ ]:
#Dependent variable y 
y = data.iloc[:, 60].values
print(y)

['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']


In [ ]:
# Encoding the categorical data (y)
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(X.shape)
print(y.shape)

(208, 59)
(208,)


In [ ]:
#CASE-1:
clf = LogisticRegression(tol=1e-4, random_state=0, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8317307692307693

In [ ]:
#CASE -2:
clf =LogisticRegression(tol=1e-4, random_state=89, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8317307692307693

In [ ]:
#CASE -3:
clf =LogisticRegression(tol=1e-4, random_state=35, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8317307692307693

In [ ]:
#CASE -4:
clf =LogisticRegression(penalty='none',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


1.0

In [ ]:
#CASE -5:
clf =LogisticRegression(penalty='l2',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8317307692307693

In [ ]:
#CASE -6:
clf =LogisticRegression(solver='newton-cg',penalty='l2',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8317307692307693

In [ ]:
#CASE -6:
clf =LogisticRegression(solver='newton-cg',penalty='none',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


1.0

In [ ]:
#CASE -7:
clf =LogisticRegression(solver='liblinear',penalty='l1',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 0]
Accuracy : 


0.8076923076923077

In [ ]:
#CASE -9:
clf =LogisticRegression(solver='saga',penalty='l1',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 0]
Accuracy : 


0.8269230769230769

In [ ]:
#CASE -10:
clf =LogisticRegression(solver='saga',penalty='l2',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8317307692307693

In [ ]:
#CASE -11:
clf =LogisticRegression(solver='saga',penalty='none',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[0 1]
Accuracy : 


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,


0.8846153846153846

In [ ]:
#CASE -12:
clf =LogisticRegression(solver='saga',penalty='l1',multi_class='auto',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 0]
Accuracy : 


0.8269230769230769

In [ ]:
#CASE -13:
clf =LogisticRegression(solver='saga',penalty='l2',multi_class='multinomial',tol=1e-4, random_state=92, max_iter=1000)
clf.fit(X,y)
pred=clf.predict(X[:2, :])
print(pred)
print('Accuracy : ')
clf.score(X, y)

[1 1]
Accuracy : 


0.8461538461538461