In [ ]:
# IMPORTING THE LIBRARIES
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report , confusion_matrix

In [ ]:
#IMPORTING THE DATA FROM CSV FILE
data = pd.read_csv(r'/content/sample_data/sonar_data.csv')
data['Label'].replace(['R', 'M'],[0, 1], inplace=True)
print(data)
print(data.head())
print(data['Label'].unique())

     Freq_1  Freq_2  Freq_3  Freq_4  ...  Freq_58  Freq_59  Freq_60  Label
0    0.0200  0.0371  0.0428  0.0207  ...   0.0084   0.0090   0.0032      0
1    0.0453  0.0523  0.0843  0.0689  ...   0.0049   0.0052   0.0044      0
2    0.0262  0.0582  0.1099  0.1083  ...   0.0164   0.0095   0.0078      0
3    0.0100  0.0171  0.0623  0.0205  ...   0.0044   0.0040   0.0117      0
4    0.0762  0.0666  0.0481  0.0394  ...   0.0048   0.0107   0.0094      0
..      ...     ...     ...     ...  ...      ...      ...      ...    ...
203  0.0187  0.0346  0.0168  0.0177  ...   0.0115   0.0193   0.0157      1
204  0.0323  0.0101  0.0298  0.0564  ...   0.0032   0.0062   0.0067      1
205  0.0522  0.0437  0.0180  0.0292  ...   0.0138   0.0077   0.0031      1
206  0.0303  0.0353  0.0490  0.0608  ...   0.0079   0.0036   0.0048      1
207  0.0260  0.0363  0.0136  0.0272  ...   0.0036   0.0061   0.0115      1

[208 rows x 61 columns]
   Freq_1  Freq_2  Freq_3  Freq_4  ...  Freq_58  Freq_59  Freq_60  Label
0 

In [ ]:
#SPLITTING THE DATA INTO TRAIN DATA AND TEST DATA
X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,random_state=1)
print(X_train.shape)
print(y_test.shape)

(75, 20)
(25,)


## ***SOME OF THE BASIC PARAMETERS FOR MULTILAYER PERCEPTRON AND OBSERVING THE CHANGE IN ACCURACY VALUES AND CONFUSION MATRIX ***

In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1]
0.88
[[12  1]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89        13
           1       0.91      0.83      0.87        12

    accuracy                           0.88        25
   macro avg       0.88      0.88      0.88        25
weighted avg       0.88      0.88      0.88        25



In [ ]:
clf = MLPClassifier(random_state=0, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1]
0.84
[[11  2]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        13
           1       0.83      0.83      0.83        12

    accuracy                           0.84        25
   macro avg       0.84      0.84      0.84        25
weighted avg       0.84      0.84      0.84        25



In [ ]:
clf = MLPClassifier(alpha = 0.009, max_iter=200).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1]
0.88
[[12  1]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89        13
           1       0.91      0.83      0.87        12

    accuracy                           0.88        25
   macro avg       0.88      0.88      0.88        25
weighted avg       0.88      0.88      0.88        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.5, max_iter=200).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.96
[[13  0]
 [ 1 11]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.92      0.96        12

    accuracy                           0.96        25
   macro avg       0.96      0.96      0.96        25
weighted avg       0.96      0.96      0.96        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.009, max_iter=200, activation = 'tanh').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.009, max_iter=200, activation = 'logistic').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0]
0.88
[[13  0]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.81      1.00      0.90        13
           1       1.00      0.75      0.86        12

    accuracy                           0.88        25
   macro avg       0.91      0.88      0.88        25
weighted avg       0.90      0.88      0.88        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.009, max_iter=200, activation = 'identity').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.05, max_iter=300, solver = 'sgd').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.05, max_iter=300, solver = 'adam').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1]
0.84
[[11  2]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        13
           1       0.83      0.83      0.83        12

    accuracy                           0.84        25
   macro avg       0.84      0.84      0.84        25
weighted avg       0.84      0.84      0.84        25



In [ ]:
clf = MLPClassifier(alpha = 0.05, max_iter=300, solver = 'lbfgs').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [ ]:
clf = MLPClassifier(alpha = 0.9, shuffle = True, solver = 'adam').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.9, shuffle = False, solver = 'adam').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.9, shuffle = True, solver = 'adam', max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.4,batch_size=20, max_iter = 700).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



In [ ]:
clf = MLPClassifier(alpha = 0.4,batch_size=70, max_iter = 700).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



In [ ]:
clf = MLPClassifier(alpha = 0.4,batch_size=80, max_iter = 700).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:612: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  "Got `batch_size` less than 1 or larger than "


[1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.92
[[13  0]
 [ 2 10]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      0.83      0.91        12

    accuracy                           0.92        25
   macro avg       0.93      0.92      0.92        25
weighted avg       0.93      0.92      0.92        25



In [ ]:
clf = MLPClassifier(alpha = 0.4,power_t=0.6, solver='sgd').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0]
0.8
[[12  1]
 [ 4  8]]
              precision    recall  f1-score   support

           0       0.75      0.92      0.83        13
           1       0.89      0.67      0.76        12

    accuracy                           0.80        25
   macro avg       0.82      0.79      0.79        25
weighted avg       0.82      0.80      0.80        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.4,power_t=0.9, solver='sgd').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
0.96
[[13  0]
 [ 1 11]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.92      0.96        12

    accuracy                           0.96        25
   macro avg       0.96      0.96      0.96        25
weighted avg       0.96      0.96      0.96        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.4,momentum=0.6, solver='sgd').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0]
0.84
[[12  1]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.86        13
           1       0.90      0.75      0.82        12

    accuracy                           0.84        25
   macro avg       0.85      0.84      0.84        25
weighted avg       0.85      0.84      0.84        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
clf = MLPClassifier(alpha = 0.4,momentum=0.8, solver='sgd').fit(X_train, y_train)
clf.predict_proba(X_test[:1])
pred = clf.predict(X_test)
print(pred)
print(clf.score(X_test, y_test))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0]
0.84
[[12  1]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.86        13
           1       0.90      0.75      0.82        12

    accuracy                           0.84        25
   macro avg       0.85      0.84      0.84        25
weighted avg       0.85      0.84      0.84        25



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
