In [ ]:
#Importing Required libraries
import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [ ]:
# Importing & Reading the dataset
df = pd.read_csv(r'/content/sample_data/artificialchar.csv')

In [ ]:
#Displaying the dataframe contents
df.head(10)

V1  V2  V3  V4  V5     V6     V7  Class
0   0   0   0   0  20  20.00  46.10      1
1   1  19   0  19   8   8.00  46.10      1
2   2   0  20  19   8  22.47  46.10      1
3   3   0  20   8  42  23.41  46.10      1
4   4  19   8   8  42  35.74  46.10      1
5   0   0   0   0  12  12.00  37.66      1
6   1   7   0   7   7   7.00  37.66      1
7   2   0  12   7   7   8.60  37.66      1
8   3   0  12   1  35  23.02  37.66      1
9   4   7   7   5  30  23.09  37.66      1

In [ ]:
# Our independent variables X
X = df.iloc[:, 0:7].values
X=X
print(X)

[[ 0.    0.    0.   ... 20.   20.   46.1 ]
 [ 1.   19.    0.   ...  8.    8.   46.1 ]
 [ 2.    0.   20.   ...  8.   22.47 46.1 ]
 ...
 [ 5.   22.   20.   ... 14.    7.21 49.19]
 [ 6.   18.   14.   ...  8.   18.97 49.19]
 [ 7.    0.    8.   ...  0.   21.54 49.19]]


In [ ]:
# our dependent variable y 
y = df.iloc[:, 7].values
print(y)

[1 1 1 ... 3 3 3]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(C=1.5,random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 6 5 2]
0.6203522504892368
[[162   0   8  10   1  15  13   5  76   7]
 [  0 239  74   0   8   2   0   0   2   3]
 [  2 160 179   0   5   3   5   1   3   4]
 [  3   0   0 160   0   0   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 44   2   1   2   0 124  48   1  13  14]
 [ 24   2   6   1   0  50  77   4   8  20]
 [  1   0   0  63   0   0   5 195   0   0]
 [115   0   5   4   0  17   6   2 116   5]
 [ 14   6   7   0   0  12  22   0   3 100]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(C=2.5,random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6313111545988258
[[163   3   5   8   1  15  13   4  78   7]
 [  0 237  77   0   8   1   0   0   3   2]
 [  2 155 188   0   4   2   3   1   5   2]
 [  2   0   0 163   0   0   0  28   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 42   2   1   2   0 127  44   1  16  14]
 [ 26   3   3   1   0  50  75   3  10  21]
 [  1   0   0  63   0   0   4 195   1   0]
 [105   0   4   2   0  15   7   0 132   5]
 [ 13   8   7   0   0  10  20   0   6 100]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(kernel="linear",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[8 2 3 ... 6 3 2]
0.4223091976516634
[[ 91  15  33   8   5  29   7  24  46  39]
 [  2 130 162   6  12   1   8   3   0   4]
 [ 20 136 155   5  11   8   5   7   0  15]
 [ 25   0   1  49  30  12  18  58   0   0]
 [  6   3  17   8 195   0   0   7   0   0]
 [  3  14  14   7   0 116  42   3   0  50]
 [  3  13  11   9   0  62  48   4   0  42]
 [ 11   0   7  25  16  14  16 165   1   9]
 [ 88   4  13   6   4  41   7  21  40  46]
 [  0  10   6   0   0  20  33   5   0  90]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.5581213307240704
[[201   4   1  11   2  15  11   9  36   7]
 [  6 209  82   2   7   4  12   1   1   4]
 [  7 149 168   4  12   9   6   2   3   2]
 [ 27   0   0 156   0   1   0   9   0   0]
 [  0   2   0   0 234   0   0   0   0   0]
 [ 61   4   1  22   0 103  39   1   9   9]
 [ 40   3   5   6   0  48  55  13   6  16]
 [  9   0   0  74   0   5   4 169   3   0]
 [185   2   2   4   1   7   0   7  57   5]
 [ 14   3   2   3   0   8  51   3   6  74]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(kernel="rbf",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6027397260273972
[[160   0   8   8   1  17  14   9  73   7]
 [  0 228  85   0   7   2   0   0   2   4]
 [  2 166 174   0   3   6   3   1   3   4]
 [  3   0   0 158   0   2   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 47   2   2   6   0 115  44   1  11  21]
 [ 26   3   6   0   0  51  75   5   4  22]
 [  1   0   0  61   0   3   8 191   0   0]
 [121   0   4   5   0  20   6   4 105   5]
 [ 14   4   9   0   0  10  25   0   1 101]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(kernel="sigmoid",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[ 5  7  2 ... 10  7  3]
0.17690802348336596
[[ 44  32  62   8  38  16  11  54  13  19]
 [ 20  70 112  14   0  14  28  30  35   5]
 [ 46  60 138  14   1   6  28  22  27  20]
 [ 30   4  28  14  66   9  18  23   1   0]
 [  1   3  13  24  33   4  19 105  10  24]
 [ 25  31  59  12  27  22  13  15  11  34]
 [  2  17  55  21  32  12  13   4   9  27]
 [ 12   4  41  35  69   5  15  81   1   1]
 [ 45  22  52   6  23  18  18  46  13  27]
 [  2  16  12  14  54  25   3   2  12  24]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(degree=2,kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 9 5 2]
0.5495107632093933
[[166   0  10  21   8   8   2  15  59   8]
 [  0 121 186   0   9   3   4   0   0   5]
 [  3 112 222   0   3  16   2   1   0   3]
 [  8   0   0 163   0   0   1  21   0   0]
 [  0   2   6   0 224   0   0   1   3   0]
 [ 49   3  13  17   5 105  27   4  16  10]
 [ 32   2  14   6   4  53  31  22   8  20]
 [  7   0   0  61   0   2   3 189   2   0]
 [120   1  11  23   3   5   1   7  94   5]
 [ 17   3  10   0   3  12  28   2   0  89]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(degree=3,kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.5581213307240704
[[201   4   1  11   2  15  11   9  36   7]
 [  6 209  82   2   7   4  12   1   1   4]
 [  7 149 168   4  12   9   6   2   3   2]
 [ 27   0   0 156   0   1   0   9   0   0]
 [  0   2   0   0 234   0   0   0   0   0]
 [ 61   4   1  22   0 103  39   1   9   9]
 [ 40   3   5   6   0  48  55  13   6  16]
 [  9   0   0  74   0   5   4 169   3   0]
 [185   2   2   4   1   7   0   7  57   5]
 [ 14   3   2   3   0   8  51   3   6  74]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(degree=4,kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.5722113502935421
[[205   3   5  26   5   6   6   5  30   6]
 [  3 174 124   1  11   1   9   0   3   2]
 [ 10 103 227   4   7   1  10   0   0   0]
 [  7   0   0 174   0   0   0  12   0   0]
 [  1   3   0   3 229   0   0   0   0   0]
 [ 67   0   1  47   2  85  32   2   8   5]
 [ 51   3   6  25   2  22  60  11   6   6]
 [  3   0   2  74   0   0   2 182   1   0]
 [162   0   5  28   3   1   1   0  67   3]
 [ 28   1  10   9   0   6  49   0   2  59]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(gamma="scale",kernel="rbf",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6027397260273972
[[160   0   8   8   1  17  14   9  73   7]
 [  0 228  85   0   7   2   0   0   2   4]
 [  2 166 174   0   3   6   3   1   3   4]
 [  3   0   0 158   0   2   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 47   2   2   6   0 115  44   1  11  21]
 [ 26   3   6   0   0  51  75   5   4  22]
 [  1   0   0  61   0   3   8 191   0   0]
 [121   0   4   5   0  20   6   4 105   5]
 [ 14   4   9   0   0  10  25   0   1 101]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(gamma="scale",kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.5581213307240704
[[201   4   1  11   2  15  11   9  36   7]
 [  6 209  82   2   7   4  12   1   1   4]
 [  7 149 168   4  12   9   6   2   3   2]
 [ 27   0   0 156   0   1   0   9   0   0]
 [  0   2   0   0 234   0   0   0   0   0]
 [ 61   4   1  22   0 103  39   1   9   9]
 [ 40   3   5   6   0  48  55  13   6  16]
 [  9   0   0  74   0   5   4 169   3   0]
 [185   2   2   4   1   7   0   7  57   5]
 [ 14   3   2   3   0   8  51   3   6  74]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(gamma="scale",kernel="sigmoid",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[ 5  7  2 ... 10  7  3]
0.17690802348336596
[[ 44  32  62   8  38  16  11  54  13  19]
 [ 20  70 112  14   0  14  28  30  35   5]
 [ 46  60 138  14   1   6  28  22  27  20]
 [ 30   4  28  14  66   9  18  23   1   0]
 [  1   3  13  24  33   4  19 105  10  24]
 [ 25  31  59  12  27  22  13  15  11  34]
 [  2  17  55  21  32  12  13   4   9  27]
 [ 12   4  41  35  69   5  15  81   1   1]
 [ 45  22  52   6  23  18  18  46  13  27]
 [  2  16  12  14  54  25   3   2  12  24]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(gamma="auto",kernel="rbf",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6027397260273972
[[160   0   8   8   1  17  14   9  73   7]
 [  0 228  85   0   7   2   0   0   2   4]
 [  2 166 174   0   3   6   3   1   3   4]
 [  3   0   0 158   0   2   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 47   2   2   6   0 115  44   1  11  21]
 [ 26   3   6   0   0  51  75   5   4  22]
 [  1   0   0  61   0   3   8 191   0   0]
 [121   0   4   5   0  20   6   4 105   5]
 [ 14   4   9   0   0  10  25   0   1 101]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(gamma="auto",kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.5581213307240704
[[201   4   1  11   2  15  11   9  36   7]
 [  6 209  82   2   7   4  12   1   1   4]
 [  7 149 168   4  12   9   6   2   3   2]
 [ 27   0   0 156   0   1   0   9   0   0]
 [  0   2   0   0 234   0   0   0   0   0]
 [ 61   4   1  22   0 103  39   1   9   9]
 [ 40   3   5   6   0  48  55  13   6  16]
 [  9   0   0  74   0   5   4 169   3   0]
 [185   2   2   4   1   7   0   7  57   5]
 [ 14   3   2   3   0   8  51   3   6  74]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(gamma="auto",kernel="sigmoid",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[ 5  7  2 ... 10  7  3]
0.17690802348336596
[[ 44  32  62   8  38  16  11  54  13  19]
 [ 20  70 112  14   0  14  28  30  35   5]
 [ 46  60 138  14   1   6  28  22  27  20]
 [ 30   4  28  14  66   9  18  23   1   0]
 [  1   3  13  24  33   4  19 105  10  24]
 [ 25  31  59  12  27  22  13  15  11  34]
 [  2  17  55  21  32  12  13   4   9  27]
 [ 12   4  41  35  69   5  15  81   1   1]
 [ 45  22  52   6  23  18  18  46  13  27]
 [  2  16  12  14  54  25   3   2  12  24]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.0,kernel="sigmoid",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[5 2 3 ... 8 6 2]
0.13581213307240705
[[ 13  55  75   3  65  41   3  32   0  10]
 [  8 105  77  30   0  48  22  35   3   0]
 [ 30 118  65  31   0  51  19  36   7   5]
 [  5  76  21  10  49  20   0  12   0   0]
 [ 32  21   7  15  21  46  18  72   0   4]
 [ 41  26  33  18  28  57   1  15  16  14]
 [  7  14  35  10  54  42   6   9   0  15]
 [ 26  54  12  20  76  10   0  55  11   0]
 [ 10  47  47  13  43  50   2  46   2  10]
 [ 10  14   0  21  73  17   6  10   0  13]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.5,kernel="sigmoid",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[5 2 3 ... 5 2 2]
0.1299412915851272
[[ 11  41  70   5  72  45   1  45   1   6]
 [  8 102  70  40   1  46  20  39   1   1]
 [ 29 120  63  29   0  51  16  48   2   4]
 [  4  52  23   8  62  20   0  24   0   0]
 [ 33  21   7  16  20  41  16  79   0   3]
 [ 42  23  29  23  36  55   1  22  10   8]
 [ 11  17  35  10  59  40   2   7   0  11]
 [ 26  43  11  31  80   9   0  63   1   0]
 [  7  38  43  15  56  54   0  52   0   5]
 [  7  14   0  23  75  17   7  13   0   8]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=2.5,kernel="sigmoid",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[5 2 3 ... 5 2 2]
0.1299412915851272
[[ 12  36  71   2  82  36   0  58   0   0]
 [  5 108  92  20   1  48  18  36   0   0]
 [ 37 116  74  19   0  53  12  49   1   1]
 [  5  40  26   3  80   9   0  30   0   0]
 [ 37  19  11  18  21  44   1  85   0   0]
 [ 48  23  34   8  45  44   3  40   4   0]
 [ 10  15  41   3  67  36   2  12   0   6]
 [ 29  35  11  26  94   2   0  67   0   0]
 [  9  32  50   2  65  42   0  70   0   0]
 [ 13  11   0  10  83  27   5  14   0   1]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.0,kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6371819960861057
[[166   4   2   9   1  19  12   4  73   7]
 [  0 242  71   0   6   1   0   0   5   3]
 [  5 152 190   0   5   1   4   0   3   2]
 [  3   0   0 168   0   0   0  22   0   0]
 [  0   1   1   0 234   0   0   0   0   0]
 [ 34   2   0   4   0 138  36   2  18  15]
 [ 28   3   1   1   0  52  71   5  10  21]
 [  1   0   0  65   0   0   2 195   1   0]
 [117   4   0   2   0  21   2   0 119   5]
 [ 13  12   3   0   0   9  17   0   5 105]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.5,kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6414872798434442
[[169   6   2   9   1  16  12   4  71   7]
 [  0 246  68   0   5   1   1   0   5   2]
 [  4 155 189   0   5   1   3   0   3   2]
 [  3   0   0 166   0   0   0  24   0   0]
 [  0   2   1   0 233   0   0   0   0   0]
 [ 34   2   0   4   0 138  34   2  18  17]
 [ 23   4   0   0   0  54  75   5  11  20]
 [  1   0   0  62   0   0   1 199   1   0]
 [117   4   0   2   0  19   2   0 121   5]
 [ 13  10   5   0   0   9  17   0   7 103]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=2.5,kernel="poly",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 6 5 2]
0.639921722113503
[[156   8   2   9   1  12  13   4  86   6]
 [  0 246  69   0   4   1   2   0   3   3]
 [  4 153 190   0   5   1   3   0   3   3]
 [  3   0   0 163   0   0   0  27   0   0]
 [  0   2   1   0 233   0   0   0   0   0]
 [ 27   3   0   4   0 141  32   1  25  16]
 [ 21   3   0   1   0  54  72   4  15  22]
 [  0   0   0  60   0   0   2 201   1   0]
 [109   4   0   2   0  15   2   0 133   5]
 [ 13  11   2   0   0  11  19   0   8 100]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.0,kernel="rbf",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6027397260273972
[[160   0   8   8   1  17  14   9  73   7]
 [  0 228  85   0   7   2   0   0   2   4]
 [  2 166 174   0   3   6   3   1   3   4]
 [  3   0   0 158   0   2   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 47   2   2   6   0 115  44   1  11  21]
 [ 26   3   6   0   0  51  75   5   4  22]
 [  1   0   0  61   0   3   8 191   0   0]
 [121   0   4   5   0  20   6   4 105   5]
 [ 14   4   9   0   0  10  25   0   1 101]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.5,kernel="rbf",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6027397260273972
[[160   0   8   8   1  17  14   9  73   7]
 [  0 228  85   0   7   2   0   0   2   4]
 [  2 166 174   0   3   6   3   1   3   4]
 [  3   0   0 158   0   2   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 47   2   2   6   0 115  44   1  11  21]
 [ 26   3   6   0   0  51  75   5   4  22]
 [  1   0   0  61   0   3   8 191   0   0]
 [121   0   4   5   0  20   6   4 105   5]
 [ 14   4   9   0   0  10  25   0   1 101]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=2.5,kernel="rbf",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[4 2 1 ... 1 5 2]
0.6027397260273972
[[160   0   8   8   1  17  14   9  73   7]
 [  0 228  85   0   7   2   0   0   2   4]
 [  2 166 174   0   3   6   3   1   3   4]
 [  3   0   0 158   0   2   0  30   0   0]
 [  0   3   0   0 233   0   0   0   0   0]
 [ 47   2   2   6   0 115  44   1  11  21]
 [ 26   3   6   0   0  51  75   5   4  22]
 [  1   0   0  61   0   3   8 191   0   0]
 [121   0   4   5   0  20   6   4 105   5]
 [ 14   4   9   0   0  10  25   0   1 101]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.0,kernel="linear",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[8 2 3 ... 6 3 2]
0.4223091976516634
[[ 91  15  33   8   5  29   7  24  46  39]
 [  2 130 162   6  12   1   8   3   0   4]
 [ 20 136 155   5  11   8   5   7   0  15]
 [ 25   0   1  49  30  12  18  58   0   0]
 [  6   3  17   8 195   0   0   7   0   0]
 [  3  14  14   7   0 116  42   3   0  50]
 [  3  13  11   9   0  62  48   4   0  42]
 [ 11   0   7  25  16  14  16 165   1   9]
 [ 88   4  13   6   4  41   7  21  40  46]
 [  0  10   6   0   0  20  33   5   0  90]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=1.5,kernel="linear",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[8 2 3 ... 6 3 2]
0.4223091976516634
[[ 91  15  33   8   5  29   7  24  46  39]
 [  2 130 162   6  12   1   8   3   0   4]
 [ 20 136 155   5  11   8   5   7   0  15]
 [ 25   0   1  49  30  12  18  58   0   0]
 [  6   3  17   8 195   0   0   7   0   0]
 [  3  14  14   7   0 116  42   3   0  50]
 [  3  13  11   9   0  62  48   4   0  42]
 [ 11   0   7  25  16  14  16 165   1   9]
 [ 88   4  13   6   4  41   7  21  40  46]
 [  0  10   6   0   0  20  33   5   0  90]]


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
clf = make_pipeline(StandardScaler(), SVC(coef0=2.5,kernel="linear",random_state = 0)).fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)
print(clf.score(X_test,y_test))
cm = confusion_matrix(y_test, y_pred)
print(cm)

[8 2 3 ... 6 3 2]
0.4223091976516634
[[ 91  15  33   8   5  29   7  24  46  39]
 [  2 130 162   6  12   1   8   3   0   4]
 [ 20 136 155   5  11   8   5   7   0  15]
 [ 25   0   1  49  30  12  18  58   0   0]
 [  6   3  17   8 195   0   0   7   0   0]
 [  3  14  14   7   0 116  42   3   0  50]
 [  3  13  11   9   0  62  48   4   0  42]
 [ 11   0   7  25  16  14  16 165   1   9]
 [ 88   4  13   6   4  41   7  21  40  46]
 [  0  10   6   0   0  20  33   5   0  90]]
